# Generated by Django 5.1.2 on 2024-10-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_author1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destinations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="pics")),
                ("desc", models.TextField()),
                ("price", models.IntegerField()),
                ("offer", models.BooleanField(default=False)),
            ],
        ),
    ]
