# Generated by Django 5.1.2 on 2024-10-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_destinations"),
    ]

    operations = [
        migrations.AddField(
            model_name="author1",
            name="book_price",
            field=models.IntegerField(default=100),
        ),
    ]
